--------------------------------------------------------
--  File created - Tuesday-November-03-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TWITTERFEEDS
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."TWITTERFEEDS" 
   (	"POSTID" NUMBER(*,0), 
	"POST" VARCHAR2(500 BYTE), 
	"USERID" NUMBER(*,0), 
	"POST_DATE" DATE, 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TWITTERUSERS
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."TWITTERUSERS" 
   (	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PWD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTUSERDB.TWITTERFEEDS
SET DEFINE OFF;
Insert into TESTUSERDB.TWITTERFEEDS (POSTID,POST,USERID,POST_DATE,USERNAME) values (1,'This is a cool night.',1,to_date('02-NOV-15','DD-MON-RR'),'Lily');
Insert into TESTUSERDB.TWITTERFEEDS (POSTID,POST,USERID,POST_DATE,USERNAME) values (2,'This is a cool night.',1,to_date('02-NOV-15','DD-MON-RR'),'Lily');
Insert into TESTUSERDB.TWITTERFEEDS (POSTID,POST,USERID,POST_DATE,USERNAME) values (3,'Today is my lucky day. Woo~~~',2,to_date('02-NOV-15','DD-MON-RR'),'Lucy');
REM INSERTING into TESTUSERDB.TWITTERUSERS
SET DEFINE OFF;
Insert into TESTUSERDB.TWITTERUSERS (USERID,USERNAME,PWD) values (1,'Lily','123456');
Insert into TESTUSERDB.TWITTERUSERS (USERID,USERNAME,PWD) values (2,'Lucy','123456');
--------------------------------------------------------
--  DDL for Index SYS_C007584
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."SYS_C007584" ON "TESTUSERDB"."TWITTERFEEDS" ("POSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007583
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."SYS_C007583" ON "TESTUSERDB"."TWITTERUSERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TWITTERFEEDS
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."TWITTERFEEDS" ADD PRIMARY KEY ("POSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TWITTERUSERS
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."TWITTERUSERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
